#!/bin/sh
if [ -f ~/jenkins.war ]
then
	echo 'Found jenkins installation.'
else
	echo 'Installing jenkins.'
	wget -O ~/jenkins.war http://ftp-chi.osuosl.org/pub/jenkins/war/1.449/jenkins.war
fi
echo 'Installing dotCloud scaffolding.'
cp -a jenkins/. ~
